"use client"

import localFont from "next/font/local";
import "./globals.css";
import { SiteSettingsProvider, useSiteSettings } from './context/SiteSettingsContext';
import { useState, useEffect } from "react";
import Head from "next/head";

function LayoutContent({ children }) {
  const { siteSettings, isLoading } = useSiteSettings();
  const [title, setTitle] = useState("Lumina Blue");

  useEffect(() => {
    if (siteSettings?.name) {
      setTitle(siteSettings.name);
    }
  }, [siteSettings]);

  return (
    <html lang="en">
      <Head>
        <title>{isLoading ? "Loading..." : title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      
      <body className={`antialiased flex flex-col min-h-screen w-full`}>
        <main className="flex-grow w-full">
          {children}
        </main>
      </body>
    </html>
  );
}

export default function RootLayout({ children }) {
  return (
    <SiteSettingsProvider>
      <LayoutContent>{children}</LayoutContent>
    </SiteSettingsProvider>
  );
}
